### ISSUE TITLE
can't create divs

### ISSUE THREAD

**Issue by jcesarmobile** [willmartindev/div.js#1] opened 2021-06-18 16:12 UTC
Added
```
<div is="div">
      <div is="p">hello</div>
</div>
```
and my page hangs

please, fix ASAP

**Comment by Pika-Pool** [comment] 2021-06-18 16:50
Lol nice catch. Its a simple fix. Just use the selector `div[is]:not([is="div"])`. Or just remove the `is` attribute when adding attributes in `swapDivs`

@willmartindev , I would love to add a pull request if you could tell me which method u like better😄😄

**Comment by Vinnl** [comment] 2021-06-18 18:06
Any updates on this? It's been two hours and still no fix, making this library literally unusable. I'm going back to canvas.js.

**Comment by willmartian** [comment] 2021-06-18 18:13
@jcesarmobile Thank you for the issue and the code reproduction.

@Vinnl Sorry!!! This project's popularly has gone to the moon and I have been trying to keep up with all of the open issues 

@Pika-Pool a PR removing the `is` attribute after swapping would be very helpful! Feel free to PR! Yay #opensource 🌈

**Comment by Vinnl** [comment] 2021-06-18 18:22
(@willmartindev To emphasise because I'm starting to feel guilty, I was parodying entitled comments on GitHub issues, I'm not actually angry :P )

**Comment by willmartian** [comment] 2021-06-18 18:23
> (@willmartindev To emphasise because I'm starting to feel guilty, I was parodying entitled comments on GitHub issues, I'm not actually angry :P )

Oh yeah I got you and I thought it was funny! Carry on mate :)

**Comment by willmartian** [comment] 2021-06-18 18:34
Closing a la #2, great work everyone!

**Closed as completed by willmartian** 2021-06-18 18:34 UTC
